services:
  cv-builder:
    build:
      context: .
      dockerfile: Dockerfile
    image: ehsancv/latex:latest
    working_dir: /work
    volumes:
      - .:/work
    environment:
      - OUTDIR=pdf
      - AUXDIR=build
    command: []
